### ISSUE TITLE
[html-to-structured-text] Consider supporting 'br' structured element

### ISSUE THREAD

**Issue by slightly-askew** [datocms/structured-text#10]
Hello!

I tried to create a multiline blockquote in the markdown editor like so:

```
> You have brains in your head. 
> You have feet in your shoes. 
> You can steer yourself in any direction you choose.
```

However, the text above is rendered in a single line:

```
<p>You have brains in your head.You have feet in your shoes.You can steer yourself in any direction you choose.</p>
```

I tracked the issue through remark steps (adding a plugin to ensure `<br>` is generated in the hast) and then through the parse5 steps. A node is being passed to `parse5ToStructuredText`:

```json
{
    "type": "element",
    "tagName": "br",
    "properties": {},
    "children": []
}
```

However, the object seems to be ignored as it is not in the schema as far as I can tell. Instead, we get 

```json
{
    "children": [
        {
            "children": [
                {
                    "value": "You have brains in your head. ",
                    "type": "span"
                },
                {
                    "value": "You have feet in your shoes.",
                    "type": "span"
                },
                {
                    "value": "You can steer yourself in any direction you choose.",
                    "type": "span"
                }
            ],
            "type": "paragraph"
        }
    ],
    "type": "blockquote"
}
```

This tree will not be rendered on separate lines, nor does it seem correct to write a custom `renderRule` since the Array format of children is also used for adding `marks`.

This happens when trying to add trailing whitespace (2x spaces) or `<br>` at the end of a plain line (I have `rehype-raw` set up to render HTML tags in the markdown).

Would it be possible to consider including the `br` element in your schema please, or do you have any advice on how I might overcome it some other way?

Thank you!

**Comment by stefanoverna** [comment]
This is a bug, br should be supported inside blockquotes! Thanks for reporting, we'll get this fixed! /cc @giuseppeg

**Comment by stefanoverna** [comment]
v1.0.12 should solve this!
