### ISSUE TITLE
The usage examples don't work.

### ISSUE THREAD

**Issue by Jorenm** [datocms/structured-text#13]
Running just this:

`import { render } from 'datocms-structured-text-to-html-string';

render({
  schema: 'dast',
  document: {
    type: 'root',
    children: [
      {
        type: 'paragraph',
        children: [
          {
            type: 'span',
            value: 'Hello world!',
          },
        ],
      },
    ],
  },
}); `

Results in this error: RenderError: Don't know how to render a node with type "undefined". Please specify a custom renderRule for it!

**Comment by Jorenm** [comment]
Docs are wrong. It expects the document object, not the value returned by Dato.

This works:

```import { render } from 'datocms-structured-text-to-html-string';

render({
    type: 'root',
    children: [
      {
        type: 'paragraph',
        children: [
          {
            type: 'span',
            value: 'Hello world!',
          },
        ],
      },
    ]
});

**Comment by stefanoverna** [comment]
Thanks for noticing! The latest package version fixes this issue!

**Comment by owensco** [comment]
Hey, just ran into this.

`data` is the object I care about returned in my graphql query.

This does NOT work:
`render(data)`

But this DOES:
`render(data.about.value.document)`

Can I avoid this traversing, or must the `render` function only be applied to the `document` key?

**Comment by stefanoverna** [comment]
Hi, can you please paste the value contained in the `data` variable? thanks!
