### ISSUE TITLE
datocms-structured-text-to-markdown-string ?

### ISSUE THREAD

**Issue by jbtheard** [datocms/structured-text#16]
Hey there, I'd need to convert my structured content to markdown.

What's the recommended way? I guess it would be quite easy for you to add a datocms-structured-text-to-markdown package similar to datocms-structured-text-to-html-string

**Comment by stefanoverna** [comment]
Yes, we've a generic "structured text to [something else]" logic here that can be used for that: https://github.com/datocms/structured-text/blob/main/packages/utils/src/render.ts

Right now there's no such package, and we have no ETA at the moment, but we'll probably work on it in the near future!

**Comment by jbtheard** [comment]
awesome!
