### ISSUE TITLE
table or markdown table support

### ISSUE THREAD

**Issue by OAyomide** [datocms/structured-text#20]
Hi,

we're trying to implement support for tables in structured text and regular markdown syntax doesn't work. Is there a way to achieve this and if not, is this in pipeline/under consideration? right now, it's inconvenient to implement support for table.

**Comment by stefanoverna** [comment]
Hi @OAyomide. There's no plan to add native support for tables, but you can add custom blocks to handle these case. Inside the block you can ie. use this plugin to easily edit tables: https://www.datocms.com/marketplace/plugins/i/datocms-plugin-json-table
