### ISSUE TITLE
datocms-structured-text-to-html-string: <br> tags are rendered as &lt;br&gt; 

### ISSUE THREAD

**Issue by anthonyquizon** [datocms/structured-text#23]
Using the `to_html` function. If a structured text node includes a `\n` character it gets rendered it out as `&lt;br&gt;`
For example
```
    {
      "type": "heading",
      "level": 1,
      "children": [
        {
          "type": "span",
          "value": "Hello\nworld"
        }
      ]
```
would result in `<h1>hello&lt;br&gt;world</h1>`.

Looks like the generated snapshot for testing this is incorrect and has masked a passing result:
https://github.com/datocms/structured-text/blob/main/packages/to-html-string/__tests__/__snapshots__/index.test.tsx.snap#L3

**Comment by stefanoverna** [comment]
You're right! Fixed in `datocms-structured-text-to-html-string` v2.0.2
