### ISSUE TITLE
HastRootNode type not compatible with unist packages

### ISSUE THREAD

**Issue by moshie** [datocms/structured-text#26]
Hi,

I am trying to write a migration from markdown to structured text following the [documentation here](https://www.datocms.com/docs/structured-text/migrating-content-to-structured-text#migrating-markdown-content)

`hastToStructuredText` is using the wrong type `HastRootNode` type is not compatible with `unist` functions as they use the `Node` type:

<img width="716" alt="Screenshot 2023-01-27 at 11 07 00" src="https://user-images.githubusercontent.com/3974301/215071878-b87f9a88-824e-4816-8608-67c2ef0113c1.png">

I tried using `unist-utils-core` but that package fails with:

```
Error: Cannot find module 'unist'
    Require stack:
    - /Users/david.hewitt/Code/galleria/node_modules/.pnpm/unist-utils-core@1.0.8/node_modules/unist-utils-core/lib/nodes.js
    - /Users/david.hewitt/Code/galleria/node_modules/.pnpm/unist-utils-core@1.0.8/node_modules/unist-utils-core/lib/index.js
    - /Users/david.hewitt/Code/galleria/migrations/utils/convertImgsToBlocks.ts
```

Looks to me like `unist-utils-core` is referencing `unist` as a package but it's not a package?

Plus that package seems like a dirty fork of syntax-tree.

**Comment by sistrall** [comment]
Hi @moshie,

I investigated the problem, and there's definitely something weird going on. I don't have a solution at the moment.

I'm curious about the types you seem to have for the `find` function: according to [this](https://github.com/blahah/unist-util-find/issues/7) issue, `unist-util-find` doesn't have support for Typescript.

**Comment by moshie** [comment]
Seems like downgrading to `unist-utils-core` to `1.0.5` "fixed it" so I imagine something has changed in that package which is causing this issue.

Would be nice to see the code examples for markdown to structured text updated 🙏 

I do however have another issue which I raised on the forum here: https://community.datocms.com/t/migration-unexpected-end-of-file-undici/3721

**Comment by sistrall** [comment]
Thanks @moshie ,

I'll make sure to update the examples.
