### ISSUE TITLE
Add video block

### ISSUE THREAD

**Issue by donaldboulton** [datocms/structured-text#29]
How do you add a video block to Structured Text

**Comment by marcelofinamorvieira** [comment]
Hello @donaldboulton 

You can do so by creating a block model, and then in that block model, create a media field:

<img width="958" alt="image" src="https://github.com/datocms/structured-text/assets/44898680/b8a1d3d4-5610-4e6e-97b5-1578256a4a87">

If you want the video to be external (like an youtube or Vimeo URL) you can select the "External video" option. If you want to use a video directly from you asset area you can choose a "Single asset" or "Asset gallery" field.

Once that is done and you have your new block model with that field inside

<img width="1728" alt="image" src="https://github.com/datocms/structured-text/assets/44898680/9d6ef977-8109-4ab9-81fc-ffb4c9043e3c">

You can then go to your Structured text field in the model where it is used and click "edit field"

<img width="1727" alt="image" src="https://github.com/datocms/structured-text/assets/44898680/40e53b9c-af20-492e-930f-4b8fd0b0b8dd">

Then, go to the "Validations" tab and add the Video block we just created as a block option to that field:
And then, save the field

<img width="812" alt="image" src="https://github.com/datocms/structured-text/assets/44898680/03263cef-aea7-453d-a5fa-551d6a130b75">

After that, you will then be able to use "/video block" inside your structured text to create a video block while writing :)

**Comment by donaldboulton** [comment]
Your amazing thank you.
